/**
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) Bao Project and Contributors. All rights reserved.
 */

/*
 * ⚠ WORK IN PROGRESS -- does not boot. Kept for the next attempt.
 *
 * The idea is right for a single VM: sweep the whole peripheral space in a few
 * windows instead of naming devices one at a time, which is how autosar-onevm
 * came to cover a fifth of the manual's peripheral regions. Eleven windows here
 * against nineteen there, and they cover everything.
 *
 * What is known so far. The interrupt half of this file is fine and now lives
 * in autosar-onevm, board-verified. The mapping half stops the guest dead with
 * no CAN and no console. One cause was found and fixed and did not account for
 * it: INTC2 is 32 KB by the manual's address map, while deriving the size from
 * sizeof(struct intc2) gave 0x6000 and left its last 8 KB -- EIBD and EEIC --
 * passed through, so the guest could reprogram routing behind vintc. Take
 * peripheral extents from the manual, never from the emulation struct.
 *
 * Still to find: what else in the sweep breaks it. Bisect the windows, and get
 * a readable console first -- every round of this cost four minutes and told us
 * only "no frames", which is the same answer for every cause.
 */

/*
 * RH850/U2A16 -- the whole four-core AUTOSAR project as one VM.
 *
 * With a single VM there is nothing to partition, so this configuration is not
 * trying to divide the machine: it is trying to stay out of the way. The guest
 * gets the entire peripheral address space and every interrupt the device has,
 * and the hypervisor keeps only what it cannot share.
 *
 * That is a deliberate change of shape. The configuration this replaces was
 * assembled one block at a time across seventy board rounds, each round adding
 * whatever the guest had just died on, and it ended up covering less than a
 * fifth of the peripheral regions in the manual with eleven interrupts named
 * out of seven hundred. Every one of those gaps failed the same way -- silently
 * -- because an unmapped peripheral aborts somewhere far from the cause and an
 * unassigned interrupt is dropped by the emulated INTC without a word.
 *
 * The previous configuration is kept, buildable, as autosar-onevm-minimal.
 *
 * ---- memory ---------------------------------------------------------------
 * Four RAM regions plus the guest's flash window, as before.
 *
 * ---- peripherals ----------------------------------------------------------
 * One sweep of 0xFF000000..0xFFFFFFFF, minus the ten holes Bao has to keep for
 * itself. The holes are not optional: a device that Bao emulates must NOT be
 * mapped, because a mapped region never traps and the emulation would simply
 * never run. INTC2 is the sharpest of these -- passing it through would let the
 * guest reprogram interrupt routing behind the hypervisor's back, including the
 * lines Bao uses.
 *
 * Eleven windows where the old configuration used nineteen, and they cover
 * everything instead of a fifth of it.
 *
 * ---- interrupts -----------------------------------------------------------
 * All 701 assignable channels, generated by scripts/gen_irqs.py from the
 * manual's own interrupt table. Reserved channels are left out because
 * intc_vm_assign writes EIBD for every id it is handed and those have no
 * register; channel 3 is left out because it is the hypervisor's IPI and
 * vm_init_dev turns a refused assignment into a fatal error.
 */

#include <config.h>

/* Interrupt list generated by scripts/gen_irqs.py from Interrupt_table.xlsx, the
 * appendix of R01UH0864EJ0150 Rev.1.50. Do not edit by hand: rerun it.
 *
 * 768 channels in the table, 66 Reserved and
 * 66 absent on this product and package (column P).
 * Channel 3 is IPI_HYP_IRQ_ID and belongs to the hypervisor.
 * That leaves 635 for the VM. */
static irqid_t single_vm_irqs[] = {
    0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26,
    27, 28, 29, 30, 31, 34, 36, 38, 39, 40, 41, 42,
    43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
    55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
    67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
    79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
    91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102,
    103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
    115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
    127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
    139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
    151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
    163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
    175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186,
    187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
    199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210,
    211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222,
    223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
    235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
    247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
    259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
    271, 272, 273, 274, 275, 276, 277, 278, 279, 296, 297, 298,
    299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310,
    311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322,
    323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334,
    335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346,
    347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
    359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370,
    371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382,
    383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394,
    395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406,
    407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430,
    431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
    443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
    455, 456, 457, 458, 459, 460, 461, 462, 463, 512, 513, 514,
    515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
    527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
    539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550,
    551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562,
    563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574,
    575, 576, 577, 578, 579, 580, 581, 584, 585, 586, 587, 588,
    589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600,
    601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612,
    613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
    625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
    637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648,
    649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660,
    661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672,
    673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684,
    685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 696, 697,
    698, 699, 700, 701, 702, 703, 704, 705, 706, 715, 716,
};

#define SINGLE_VM_IRQ_NUM (sizeof(single_vm_irqs) / sizeof(single_vm_irqs[0]))

struct config config = {

    /*
     * Bao's .data/.bss default to the first RWX region (Cluster0 at
     * 0xFE000000), which is exactly the guest's main RAM. Relocate to
     * Cluster1, the one RAM block this guest never touches.
     */
    .hyp = {
        .data_relocate = true,
        .data_addr = 0xFE100000,
    },

    .vmlist_size = 1,
    .vmlist = (struct vm_config[]){
        {
            .entry = 0x10000,
            .image = VM_IMAGE_LOADED(0x10000, 0x10000, 0x400000),
            .cpu_affinity = 0xF, /* PE0..PE3 */

            .platform = {
                .cpu_num = 4,

                .region_num = 4,
                .regions = (struct vm_mem_region[]){
                    /* Guest code window: iROM_0 at 0x10000 plus dBaseROM,
                     * which the HV linker layout puts at 0x400000 so that one
                     * window covers exactly what the guest uses. */
                    { .base = 0x00010000, .size = 0x400000 },
                    /* Cluster0 RAM -- .data/.bss, PE0 stack, OS system stacks */
                    { .base = 0xFE000000, .size = 0x80000 },
                    /* Cluster2 RAM -- ETH_PORT_RAM_1, RAM_WDGM, RAM_CAL */
                    { .base = 0xFE400000, .size = 0x80000 },
                    /* Retention RAM -- .rcode */
                    { .base = 0xFE800000, .size = 0x20000 },
                },

                .dev_num = 12,
                .devs = (struct vm_dev_region[]){
                    /* Local RAM: the four per-PE views and the self alias.
                     * The self alias at 0xFDE00000 is where .Os_Clone lives --
                     * every PE sees its own local RAM at that one address. */
                    { .pa = 0xFD600000, .va = 0xFD600000, .size = 0x10000,
                      .interrupt_num = 0, .interrupts = NULL, },
                    { .pa = 0xFD800000, .va = 0xFD800000, .size = 0x10000,
                      .interrupt_num = 0, .interrupts = NULL, },
                    { .pa = 0xFDA00000, .va = 0xFDA00000, .size = 0x10000,
                      .interrupt_num = 0, .interrupts = NULL, },
                    { .pa = 0xFDC00000, .va = 0xFDC00000, .size = 0x10000,
                      .interrupt_num = 0, .interrupts = NULL, },
                    { .pa = 0xFDE00000, .va = 0xFDE00000, .size = 0x10000,
                      .interrupt_num = 0, .interrupts = NULL, },

                    /* The peripheral space, swept. Each entry runs up to the
                     * next thing Bao emulates and resumes just past it; the
                     * comment on each gap names what is being skipped. */

                    /* .. up to INTIF */
                    { .pa = 0xFF000000, .va = 0xFF000000, .size = 0x00090000,
                      .interrupt_num = SINGLE_VM_IRQ_NUM,
                      .interrupts = single_vm_irqs, },
                    /* INTIF 0xFF090000 emulated */
                    { .pa = 0xFF090240, .va = 0xFF090240, .size = 0x009137C0,
                      .interrupt_num = 0, .interrupts = NULL, },
                    /* FENC 0xFF9A3A00 emulated; resume right after it.
                     *
                     * ★ The four FEINC blocks at 0xFF9A3B00..0xFF9A3EFF are
                     * NOT holes, even though Bao registers an emulator for
                     * them: the guest OS masks FEINT during init and that has
                     * to reach the real registers. The verified configuration
                     * passes the whole 0x400 range through for exactly this
                     * reason, and punching holes here was what stopped the
                     * guest dead.
                     *
                     * So "Bao emulates it" is not the test for whether to leave
                     * a window out. The test is whether the emulation actually
                     * serves the guest; where it does not, the passthrough
                     * mapping shadows the handler and that is deliberate. */
                    { .pa = 0xFF9A3A40, .va = 0xFF9A3A40, .size = 0x0025C5C0,
                      .interrupt_num = 0, .interrupts = NULL, },
                    /* EINT 0xFFC00000 emulated; then on to INTC2 */
                    { .pa = 0xFFC00040, .va = 0xFFC00040, .size = 0x0037FFC0,
                      .interrupt_num = 0, .interrupts = NULL, },
                    /* INTC2 0xFFF80000..0xFFF87FFF emulated -- the one that
                     * matters most. Mapping it would hand the guest the routing
                     * table Bao depends on.
                     *
                     * ★ The size here is the manual's (32 KB, section 4 address
                     * map), not sizeof(struct intc2) rounded up. Deriving it
                     * from the struct gave 0x6000 and left the last 8 KB of
                     * INTC2 passed through -- EIBD and EEIC live in there, so
                     * the guest reprogrammed routing behind vintc's back and
                     * nothing worked. Take peripheral extents from the manual. */
                    { .pa = 0xFFF88000, .va = 0xFFF88000, .size = 0x0002A000,
                      .interrupt_num = 0, .interrupts = NULL, },
                    /* BOOTCTRL 0xFFFB2000 emulated -- Bao starts the secondary
                     * vcpus when the guest writes it */
                    { .pa = 0xFFFB2040, .va = 0xFFFB2040, .size = 0x00006FC0,
                      .interrupt_num = 0, .interrupts = NULL, },
                    /* IPIR 0xFFFB9000..0xFFFBAFFF emulated -- the hole runs
                     * to the next thing the manual names (TPTM at 0xFFFBB000)
                     * rather than to the end of sizeof(struct ipir_hw), which
                     * would stop at 0xFFFB9BFF and pass the rest of the block
                     * through. Same mistake as the INTC2 one above: take the
                     * extent from the manual, not from the emulation struct. */
                    { .pa = 0xFFFBB000, .va = 0xFFFBB000, .size = 0x00045000,
                      .interrupt_num = 0, .interrupts = NULL, },
                },
            },
        },
    },
};
